IGSD : IGSD.o IGSD.cpp
	g++ -I/usr/local/include/ -I/public/ig/glm/ -c IGSD.cpp  -o IGSD.o
	g++ -I/usr/local IGSD.o -lglfw  -lGLEW  -lGL -lopencv_core -lopencv_imgproc -lopencv_highgui  -lopencv_imgcodecs -oIGSD
	./IGSD
